pipeline {
    agent any

    environment {
        IMAGE_NAME = "meals"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/harsh268tyagi/meals.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t $IMAGE_NAME ."
            }
        }

        stage('Docker Run') {
            steps {
                sh "docker run -d -p 8080:8080 $IMAGE_NAME"
            }
        }
    }
}
